language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

script:
  - "./vendor/bin/phpunit --coverage-clover=coverage.xml"
  - "./vendor/bin/coverage-check clover.xml 100"
  - "./vendor/bin/infection --min-msi=100 --threads=4"
before_script:
  - composer update

env:
  global:
    secure: K46yIOysaX0qscsNZAhxN9mzaGB4H9vHw2zWlxM/2vmGNK/qlxC9kG1pvot9Qmr096Jgwjof7pSC5HGzf5IPwoBwAcPavdIzyilyx6vcnIIWo5HtYrFOuayU/63NlVj61XeQ8YlGX2m8NDWOwqEXoUdL11YVmlV6do1V4FmTBib518uPmIGNnHSoE+CZGAdt2f3v7ahsEqrHHGyZvTLc/EVj4/XDchSO1ALoAHaqmVmbBW/U+gpOhfuXgKw2ZUulSjkvsBaBe11e8uyhnG9FT/9lqj4YP9GsSTgzkh0YIH4onJmvi+Rlbf1Yk68q9UxIql520J1d/7+BUhP6FK92pY/WHw/blaHT3KeDBdCNvv+DSb+pn7+MfIXENd3lXXLnFexDWWCldJDElRpE8HG1RPUnHq7E42vXdB9VEANdoqeoPF75+GLVrezfwXJzkSQRovZRibwas9tHkSpOJnvUwZFiFfL5bWW2nCMG40l7gMbTHl/d4kPqb8iDwu3Wj2ObNj55AjJBHR3WnTJn5pNQ2MP5+evfHdMF7S+3vBDlzS4cIrIbJFwsdpYOG1QkLdseZrsP0BeEYu3ED0vKC6xMavSRLIppfhN0jWrfm9gduJS+KUy3Qw4fAavbGLYLzwftp7ujMhngxgkxE/oEzmT2azzOtnBj2YeklyK6jS45990=
