language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - 7.4snapshot
script:
  - "./vendor/bin/phpunit"
  - "./vendor/bin/infection --min-msi=95 --threads=4 --only-covered"
before_script:
  - composer update

env:
  global:
    secure: VjkYRTTcpYzBczl01PLiXyNLQIv0GE1ZFuRqiA9uMN0M0yi0agu8zO6gHu0nTEraWW+W+x6vl/NtB1Ri89JF3OJicH2xR1hSJjaNwv94HgBpOv+TB1B5yfd+2W/h+2gCgP20/ZeJqpnLymFW66MryKBJYyqCmjPp3X6jSb80+bWJTXnjlHN5R7LMc9vj1b+lwOwKbeQbY+stuGv+P94lrraEF4XvMV3Zjp/YqXyV9SSb003VcvYRokPtykX+6nF8GWH/NzLKfb7tfo+Km2ZGHVRjLYgQvOB2XuIiAG5mKzWSO7SrCcK5lQ6T954i3BFk6VGPE2Lh5uYn/4QN4xNnCwySxXC4AWXIODrx+JBp6tifYALTZW3dIrVfF96cma0PgJgTyELt0Nj/NopbPRkFFondq8E1RYG00GGXFegyexuL2iO9A9OK8X/gzwq1yjJEYyjBvziL00dRr9uVmvX60xzS8dP/UU2o7K4XHmvIADiVoNTSfO1DF0kR7mjgqLcYW5b9PQG2M2Uqhrs/WKAmbpHkI01yq6WltPJZWw6x6rIgu9q3XoWicGd+YYU6aRyFsNPEM7iu2QKE+0MHmBJohZCaQ/AXRuPjFYjZPrYs25l0hSWJd7+st0cQ+KsI529xVGk5ZcoEekAxJOKNueifK8gmiRadk0cBHLcN7grcJZ4=
